"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { CalendarRange, Plus, X, Sparkles, Loader2, Clock } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { EmptyState } from "@/components/empty-state";
import { api, type StudyPlan, type PlannerInput } from "@/lib/api";
import { minutesToHours } from "@/lib/utils";

export default function PlannerPage() {
  return (
    <AppShell>
      <PlannerInner />
    </AppShell>
  );
}

function PlannerInner() {
  const [plan, setPlan] = useState<StudyPlan | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.latestPlan()
      .then((p) => {
        setPlan(p);
        if (!p) setShowForm(true);
      })
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="px-6 lg:px-12 py-10 max-w-6xl mx-auto">
        <div className="card animate-pulse h-64" />
      </div>
    );
  }

  return (
    <div className="px-6 lg:px-12 py-10 max-w-6xl mx-auto">
      <PageHeader
        eyebrow="Study planner"
        title="Your schedule, generated by AI"
        description="Tell us what you're studying. Get a balanced week tailored to your weak topics."
        actions={
          plan && (
            <button onClick={() => setShowForm((v) => !v)} className="btn-ghost">
              {showForm ? <X className="h-4 w-4" /> : <Plus className="h-4 w-4" />}
              {showForm ? "Cancel" : "New plan"}
            </button>
          )
        }
      />

      {showForm && (
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
          <PlannerForm
            onCreated={(p) => {
              setPlan(p);
              setShowForm(false);
              toast.success("Plan created");
            }}
          />
        </motion.div>
      )}

      {plan ? <PlanView plan={plan} /> : !showForm ? (
        <EmptyState
          icon={CalendarRange}
          title="No study plan yet"
          description="Generate your first AI-powered study schedule below."
          action={
            <button onClick={() => setShowForm(true)} className="btn-primary">
              <Plus className="h-4 w-4" />
              Create a plan
            </button>
          }
        />
      ) : null}
    </div>
  );
}

function PlannerForm({ onCreated }: { onCreated: (p: StudyPlan) => void }) {
  const [subjects, setSubjects] = useState<string[]>([""]);
  const [weakTopics, setWeakTopics] = useState<string[]>([]);
  const [weakInput, setWeakInput] = useState("");
  const [goals, setGoals] = useState("");
  const [examDate, setExamDate] = useState("");
  const [hours, setHours] = useState(2);
  const [days, setDays] = useState(7);
  const [submitting, setSubmitting] = useState(false);

  function addSubject() {
    setSubjects((s) => [...s, ""]);
  }
  function removeSubject(i: number) {
    setSubjects((s) => s.filter((_, idx) => idx !== i));
  }
  function updateSubject(i: number, val: string) {
    setSubjects((s) => s.map((v, idx) => (idx === i ? val : v)));
  }

  function addWeak() {
    const v = weakInput.trim();
    if (!v) return;
    setWeakTopics((t) => [...t, v]);
    setWeakInput("");
  }
  function removeWeak(i: number) {
    setWeakTopics((t) => t.filter((_, idx) => idx !== i));
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    const cleanSubjects = subjects.map((s) => s.trim()).filter(Boolean);
    if (cleanSubjects.length === 0) {
      toast.error("Add at least one subject");
      return;
    }
    if (!goals.trim()) {
      toast.error("Describe your goal");
      return;
    }
    setSubmitting(true);
    try {
      const payload: PlannerInput = {
        subjects: cleanSubjects,
        goals,
        exam_date: examDate || null,
        weak_topics: weakTopics,
        hours_per_day: hours,
        days_to_plan: days,
      };
      const plan = await api.generatePlan(payload);
      onCreated(plan);
    } catch {
      toast.error("Plan generation failed. Try again.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <form onSubmit={submit} className="card mb-8 space-y-6">
      <div className="grid lg:grid-cols-2 gap-6">
        <div>
          <label className="label">Subjects</label>
          <div className="space-y-2">
            {subjects.map((s, i) => (
              <div key={i} className="flex gap-2">
                <input
                  value={s}
                  onChange={(e) => updateSubject(i, e.target.value)}
                  className="input flex-1"
                  placeholder={i === 0 ? "e.g. Calculus" : `Subject ${i + 1}`}
                />
                {subjects.length > 1 && (
                  <button
                    type="button"
                    onClick={() => removeSubject(i)}
                    className="px-3 rounded-xl border border-white/10 text-ink-400 hover:text-signal-bad transition"
                  >
                    <X className="h-4 w-4" />
                  </button>
                )}
              </div>
            ))}
            <button
              type="button"
              onClick={addSubject}
              className="text-xs text-accent hover:text-accent-soft inline-flex items-center gap-1"
            >
              <Plus className="h-3 w-3" /> Add subject
            </button>
          </div>
        </div>

        <div>
          <label className="label">Weak topics (optional)</label>
          <div className="flex gap-2 mb-2">
            <input
              value={weakInput}
              onChange={(e) => setWeakInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  e.preventDefault();
                  addWeak();
                }
              }}
              className="input flex-1"
              placeholder="e.g. Integration by parts"
            />
            <button type="button" onClick={addWeak} className="btn-ghost">
              <Plus className="h-4 w-4" />
            </button>
          </div>
          <div className="flex flex-wrap gap-1.5">
            {weakTopics.map((t, i) => (
              <span key={i} className="chip">
                {t}
                <button type="button" onClick={() => removeWeak(i)}>
                  <X className="h-3 w-3" />
                </button>
              </span>
            ))}
          </div>
        </div>

        <div className="lg:col-span-2">
          <label className="label">Goal</label>
          <textarea
            value={goals}
            onChange={(e) => setGoals(e.target.value)}
            rows={2}
            className="input"
            placeholder="e.g. Score 90+ on the midterm and feel solid on derivatives."
          />
        </div>

        <div>
          <label className="label">Exam date (optional)</label>
          <input
            type="date"
            value={examDate}
            onChange={(e) => setExamDate(e.target.value)}
            className="input"
          />
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="label">Hours / day</label>
            <input
              type="number"
              min={0.5}
              max={12}
              step={0.5}
              value={hours}
              onChange={(e) => setHours(Number(e.target.value))}
              className="input"
            />
          </div>
          <div>
            <label className="label">Days to plan</label>
            <input
              type="number"
              min={1}
              max={30}
              value={days}
              onChange={(e) => setDays(Number(e.target.value))}
              className="input"
            />
          </div>
        </div>
      </div>

      <button type="submit" disabled={submitting} className="btn-primary">
        {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
        {submitting ? "Generating..." : "Generate plan"}
      </button>
    </form>
  );
}

function PlanView({ plan }: { plan: StudyPlan }) {
  const days = plan.payload.days ?? [];
  const totalMin = days.reduce(
    (acc, d) => acc + d.blocks.reduce((s, b) => s + b.minutes, 0),
    0,
  );

  return (
    <div className="space-y-6">
      <div className="card">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="font-display text-2xl text-ink-50">{plan.title}</h2>
            <p className="text-xs text-ink-400 mt-1">
              {days.length} days · {minutesToHours(totalMin)} total
            </p>
          </div>
          <Clock className="h-5 w-5 text-accent" />
        </div>
      </div>

      <div className="grid gap-4">
        {days.map((day, i) => (
          <motion.div
            key={day.date}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.04 }}
            className="card"
          >
            <div className="flex items-center justify-between mb-4">
              <div>
                <div className="text-xs uppercase tracking-wider text-accent">Day {i + 1}</div>
                <h3 className="font-display text-lg text-ink-50">
                  {new Date(day.date).toLocaleDateString(undefined, {
                    weekday: "long",
                    month: "short",
                    day: "numeric",
                  })}
                </h3>
              </div>
              <div className="text-xs text-ink-400">
                {minutesToHours(day.blocks.reduce((s, b) => s + b.minutes, 0))}
              </div>
            </div>

            {day.blocks.length === 0 ? (
              <p className="text-sm text-ink-400">Rest day</p>
            ) : (
              <div className="space-y-2">
                {day.blocks.map((b, j) => (
                  <div
                    key={j}
                    className="flex items-start gap-3 rounded-lg border border-white/[0.06] bg-white/[0.02] p-3"
                  >
                    <div className="shrink-0 w-14 text-center">
                      <div className="font-display text-lg text-accent leading-none">{b.minutes}</div>
                      <div className="text-[10px] uppercase text-ink-500">min</div>
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-0.5">
                        <span className="chip">{b.subject}</span>
                      </div>
                      <div className="text-sm text-ink-100 font-medium">{b.topic}</div>
                      {b.notes && <div className="text-xs text-ink-400 mt-1">{b.notes}</div>}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </motion.div>
        ))}
      </div>
    </div>
  );
}
